sg_params:

  skill_name: 'mj_insertion'
  pre_obj_names: ['socket', 'peg']
  pre_arms: ['left', 'right']
  eff_obj_names: []
  output_dir: 'hdf5_out/insertion'

  hand_hand_dist_threshold: 0.23

  scene_yaml: 'config/aloha_scene.yaml'
  ood_scene: 'OOD_XYYAW'
  place_z_offset: 0.013
  learned_checker: true

LfD_params:
  lfd_alg: 'ACT'
