sg_params:
  h5_parent_dir: "/ssd1/aloha_data/transfer_tape"
  skill_name: 'handoff_tape'
  pre_obj_names: ['tape']
  # pre_obj_names: ['tape','plunger']
  pre_arms: ['right']
  eff_obj_names: []
  output_dir: 'hdf5_out/handoff_tape'

  left:
    grasp:
      x_threshold: 0.35
      dx_threshold: -0.7
    release:
      x_threshold: 0.2
      dx_threshold: 0.7
      clip_start: 100

  right:
    grasp:
      x_threshold: 0.35
      dx_threshold: -0.7
    release:
      x_threshold: 0.4
      dx_threshold: 0.7
      clip_start: 100

  hand_obj_dist_threshold: 0.05
  hand_hand_dist_threshold: 0.18
  lifted_threshold: 0.1
  holding_truncation: 1


LfD_params:
  lfd_alg: 'DP'
  DP_input: 
    handoff_tape: '/ssd1/chenyizhou/dp_ckpts/transfer_tape/latest.ckpt'
