sg_params:
  h5_parent_dir: "/ssd1/aloha_data/screwdriver_noisy/"
  skill_name: 'screwdriver_aloha'
  skill_type: 'bimanualOr'
  pre_obj_names: ['screwdriver']
  pre_arms: ['left']
  eff_obj_names: []
  output_dir: 'hdf5_out/screwdriver'

  left:
    grasp:
      x_threshold: 0.35
      dx_threshold: -0.7
    release:
      x_threshold: 0.2
      dx_threshold: 0.7
      clip_start: 100

  right:
    grasp:
      x_threshold: 0.35
      dx_threshold: -0.7
    release:
      x_threshold: 0.2
      dx_threshold: 0.7
      clip_start: 100

  hand_obj_dist_threshold: 0.07
  hand_hand_dist_threshold: 0.18
  lifted_threshold: 0.1
  holding_truncation: 1


LfD_params:
  lfd_alg: 'DP'
  env_type: 'real'
  DP_path: '${DIFFUSION_POLICY_ROOT}/'
  DP_input: 
  ## clean background
    # screwdriver_aloha: '/ssd1/chenyizhou/dp_ckpts/aloha_screwdriver/latest.ckpt'
  ## noisy
    # screwdriver_aloha: '/ssd1/chenyizhou/dp_ckpts/aloha_screwdriver_noisy/latest.ckpt'
  ## 20demos
    screwdriver_aloha: '/ssd1/chenyizhou/dp_ckpts/aloha_screwdriver_noisy/20demos/latest.ckpt'  
  # ## long-horizon
  #   screwdriver_aloha: '/ssd1/chenyizhou/dp_ckpts/aloha_screw_sponge_cup/25steps-latest.ckpt'