socket_info:
  obj_name: 'socket'
  obj_id: -1
  x: -0.1
  y: 0.1
  yaw: 0.97
  l: 0.02
  w: 0.02
  h: 0.12

peg_info:
  obj_name: 'peg'
  obj_id: -1
  x: -0.15
  y: -0.1
  yaw: -3.4
  l: 0.12
  w: 0.08
  h: 0.08

colObs_info:
  obj_name: 'colObs'
  obj_id: -1
  x: 0.0
  y: 0.0
  yaw: 0.9
  l: 0.2
  w: 0.04
  h: 0.04

is_record: False
cmd_path: 'pkl_logs/'
