  (:action pick
    :parameters (?a ?g ?o ?p ?aq ?at)
    :precondition (and (CanPick ?o)
                       (not (Supporting ?o))
                       (Pick ?a ?o ?p ?g ?aq ?at)
                       (AtPose ?o ?p){{REACHABLE_PRE}}
                       (ArmEmpty ?a)
                       (AtConf ?a ?aq)
                       (not (UnsafePregrasp ?a ?o ?p ?g))
                       (not (UnsafeTraj ?a ?at)))
    :effect (and (AtGrasp ?a ?o ?g)
                 (CanMove ?a)
                 (ArmHolding ?a ?o)
                 (Holding ?o)
                 (HasPicked ?o)
                 (not (AtPose ?o ?p))
                 (not (ArmEmpty ?a))
                ;  (not (ConfidentInPose ?o ?p))
                 
                 ))
