  (:action learnedPick_{{ACTION_IDX}}
    :parameters (?arm ?obj ?sk ?p ?lg ?aq ?at)
    :precondition (and ({{ARM}} ?arm) ({{OBJ}} ?obj) ({{SK}} ?sk)
                      (CanPick ?obj) (AtPose ?obj ?p)
                        (not (Supporting ?obj))
                        (LearnedPick ?arm ?obj ?p ?lg ?aq ?at)
                        (ArmEmpty ?arm)
                        (ImitateGrasp ?sk ?arm ?obj ?lg)
                        (AtConf ?arm ?aq)
                  )
    :effect (and (AtGrasp ?arm ?obj ?lg) (CanMove ?arm)
                  (ArmHolding ?arm ?obj) (Holding ?obj)
                  (HasPicked ?obj)
                  (not (AtPose ?obj ?p)) (not (ArmEmpty ?arm))
                  ; (not (ConfidentInPose ?obj ?p))
                  (DoneSkill ?sk ) 
                  )
  )
