  (:action place
    :parameters (?a ?g ?o ?p ?s ?sp ?aq ?at)
    :precondition (and (Place ?a ?o ?p ?g ?aq ?at)
                       (Supported ?o ?p ?s ?sp){{REACHABLE_PRE}}
                       (AtGrasp ?a ?o ?g)
                       (AtPose ?s ?sp)
                       (AtConf ?a ?aq)
                       (not (UnsafePose ?o ?p))
                       (not (UnsafePregrasp ?a ?o ?p ?g))
                       (not (UnsafeTraj ?a ?at)))
    :effect (and (AtPose ?o ?p)
                 (ArmEmpty ?a)
                 (CanMove ?a)
                 (not (AtGrasp ?a ?o ?g))
                 (not (ArmHolding ?a ?o))
                 (not (Holding ?o))))
