  (:action Transit
    :parameters (?j ?q1 ?q2 ?t)
    :precondition (and (Motion ?j ?q1 ?q2 ?t)
                        (ArmEmpty ?j)
                       (CanMove ?j)
                      ;  (or (not (OtherActive ?j)) (not (OtherNotAtKP ?j)))
                       (AtConf ?j ?q1))
    :effect (and (AtConf ?j ?q2)
                 (not (AtConf ?j ?q1))
                 (not (CanMove ?j))))