## problems: when obj inside the bin, the pc is very sparse. if we decide when the obj is lifted, and bin is partially obstructed, then kdtree distance is not accurate. 
use_gui: True
teleport: True
robot_name: 'pandadual'
vid_save_path: 'lfd_tamp_vids'
text_prompt:  ['payload', 'trash', 'transport_start_bin_lid']
diffgen_data_path: '/home/user/yzchen_ws/imitation_learning/dexmimicgen/'
env_dir: '/home/user/yzchen_ws/imitation_learning/dexmimicgen/'

sg_params:
  task_name: 'two_arm_transport'
  robots: ['robot0', 'robot1']
  interested_objs: 
    'transport_start_bin_lid': ['Movable', 'Graspable', 'CanPick', 'Exposed']
    'transport_start_bin': ['Exposed']
    'transport_target_bin': ['Exposed']
    'transport_trash_bin': ['Exposed']
    'payload': ['Movable', 'Graspable', 'CanPick']
    'trash': ['Movable', 'Graspable', 'CanPick', 'Exposed']

  interested_skills:
    grasp_payload:
      type: 'Grasp'
      side: 'left'
      conditioned_objects: ['payload']
    grasp_trash:
      type: 'grasp'
      side: 'right'
      conditioned_objects: ['trash']
    grasp_transport_start_bin_lid:
      type: 'grasp'
      side: 'left'
      conditioned_objects: ['transport_start_bin_lid']

  hand_hand_dist_threshold: 0.35
  hand_obj_dist_threshold: 0.13
  obj_obj_dist_threshold: 0.02
  lifted_threshold: 0.02
  
  grasp:
    x_threshold: 0.025
    dx_threshold: -0.02
  release:
    x_threshold: 0.035
    dx_threshold: 0.02
    clip_start: 100


  learned_checker: False

  output_dir: 'hdf5_out/two_arm_transport'


  num_points: 256
  img_width: 168
  img_height: 168

  output_dir: 'hdf5_out/two_arm_transport'

  skillwise_sgs_path: 'datasets/pc_demos/two_arm_transport/raw/two_arm_transport_demo_0_pcd.hdf5'

  LfD_controller: 'OSC_POSE'

LfD_params:
  lfd_alg: 'DMG'